"""Generate docs/coverage.md from the installed aiogram version.

Run: python scripts/gen_coverage.py
CI regenerates the table and fails if the committed copy is stale.
"""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path
from typing import Any

import aiogram
import aiogram.methods as methods_module
from aiogram.methods import TelegramMethod

from teremok.responses import classify

STATUS = {
    "curated": "✅ Curated",
    "generic": "🟡 Generic",
    "planned": "📋 Planned",
}

OUTPUT = Path(__file__).resolve().parents[1] / "docs" / "coverage.md"


def iter_methods() -> Iterator[type[TelegramMethod[Any]]]:
    for name in sorted(methods_module.__all__):
        obj = getattr(methods_module, name)
        if (
            isinstance(obj, type)
            and issubclass(obj, TelegramMethod)
            and obj is not TelegramMethod
        ):
            yield obj


def _type_name(returning: Any) -> str:
    return getattr(returning, "__name__", None) or str(returning)


def render() -> str:
    lines = [
        "# Telegram Bot API coverage",
        "",
        f"Auto-generated by `scripts/gen_coverage.py` against aiogram "
        f"{aiogram.__version__}. Do not edit by hand.",
        "",
        "Every method is always **captured** in `bot.requests` - interception happens",
        "at the session seam, below all methods. The status below describes only the",
        "fidelity of the **auto-response** when you don't queue a result:",
        "",
        "- ✅ **Curated** - dedicated realistic auto-response, covered by tests",
        "- 🟡 **Generic** - generic auto-response (`True` for bool-returning methods,",
        "  synthesized `Message` where applicable)",
        "- 📋 **Planned** - no auto-response yet; queue one with `bot.add_result(...)`",
        "",
        "| Method | Returns | Status |",
        "|---|---|---|",
    ]
    for cls in iter_methods():
        returning = getattr(cls, "__returning__", None)
        status = STATUS.get(classify(cls), "UNKNOWN")
        lines.append(f"| `{cls.__name__}` | `{_type_name(returning)}` | {status} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
