"""Generate docs/coverage.md from the installed aiogram version.

Run: python scripts/gen_coverage.py
CI regenerates the table and fails if the committed copy is stale.
"""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path
from typing import Any

import aiogram
import aiogram.methods as methods_module
from aiogram.methods import TelegramMethod
from aiogram.types import Update

from teremok.responses import classify

STATUS = {
    "curated": "✅ Curated",
    "generic": "🟡 Generic",
    "planned": "📋 Planned",
}

# Update types with a dedicated typed builder (name -> the builder(s) to use).
# Everything else in Update.model_fields goes through the MockUpdate escape
# hatch: MockUpdate(<field>=...) dispatches any update type - you construct
# the payload yourself with real aiogram types.
DEDICATED_BUILDERS = {
    "message": (
        "`MockMessageText` / `MockMessagePhoto` / `MockMessageDocument` / "
        "`MockMessageVoice`"
    ),
    "callback_query": "`MockCallbackQuery`",
}

OUTPUT = Path(__file__).resolve().parents[1] / "docs" / "coverage.md"


def iter_methods() -> Iterator[type[TelegramMethod[Any]]]:
    for name in sorted(methods_module.__all__):
        obj = getattr(methods_module, name)
        if (
            isinstance(obj, type)
            and issubclass(obj, TelegramMethod)
            and obj is not TelegramMethod
        ):
            yield obj


def iter_update_types() -> Iterator[str]:
    for name in Update.model_fields:
        if name == "update_id":
            continue
        yield name


def _type_name(returning: Any) -> str:
    return getattr(returning, "__name__", None) or str(returning)


def render_update_types() -> list[str]:
    lines = [
        "## Update types",
        "",
        "Every field on `aiogram.types.Update` (i.e. every kind of update Telegram",
        "can deliver). `message` and `callback_query` have dedicated typed builders;",
        "everything else goes through the `MockUpdate` escape hatch - build the",
        "payload with real aiogram types and pass it as the matching keyword:",
        "`MockUpdate(<field>=...)`.",
        "",
        "- ✅ **Dedicated builder** - a typed helper builds the payload for you",
        "- 🟡 **Via escape hatch** - `MockUpdate(<field>=...)` dispatches it; you",
        "  construct the payload with aiogram types",
        "",
        "| Update type | Status | How to build |",
        "|---|---|---|",
    ]
    for name in iter_update_types():
        if name in DEDICATED_BUILDERS:
            lines.append(f"| `{name}` | ✅ Dedicated builder | {DEDICATED_BUILDERS[name]} |")
        else:
            lines.append(f"| `{name}` | 🟡 Via escape hatch | `MockUpdate({name}=...)` |")
    lines.append("")
    return lines


def render_methods() -> list[str]:
    lines = [
        "## Methods",
        "",
        "Every method is always **captured** in `bot.requests` - interception happens",
        "at the session seam, below all methods. The status below describes only the",
        "fidelity of the **auto-response** when you don't queue a result:",
        "",
        "- ✅ **Curated** - dedicated realistic auto-response, covered by tests",
        "- 🟡 **Generic** - generic auto-response (`True` for bool-returning methods,",
        "  synthesized `Message` where applicable)",
        "- 📋 **Planned** - no auto-response yet; queue one with `bot.add_result(...)`",
        "",
        "| Method | Returns | Status |",
        "|---|---|---|",
    ]
    for cls in iter_methods():
        returning = getattr(cls, "__returning__", None)
        status = STATUS.get(classify(cls), "UNKNOWN")
        lines.append(f"| `{cls.__name__}` | `{_type_name(returning)}` | {status} |")
    return lines


def render() -> str:
    lines = [
        "# Telegram Bot API coverage",
        "",
        f"Auto-generated by `scripts/gen_coverage.py` against aiogram "
        f"{aiogram.__version__}. Do not edit by hand.",
        "",
    ]
    lines += render_update_types()
    lines += render_methods()
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
